[project]
name = "hack4humanity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "catboost>=1.2.10",
    "ipykernel>=7.4.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "onnx>=1.23.1",
    "onnxruntime>=1.30.0",
    "opencv-python-headless>=5.0.0.93",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.1",
    "scipy>=1.17.1",
    "streamlit>=1.64.0",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
    "tqdm>=4.70.1",
]
